# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  (1..3).each do |i|
    config.vm.define "server#{i}" do |c|
      c.vm.hostname = "server#{i}"
      c.vm.box = "ubuntu/trusty64"
      c.vm.network :private_network, ip: "10.0.0.1#{i}"
	  c.vm.provision :hosts, :sync_hosts => true
      c.vm.provider :virtualbox do |v|
        v.memory = 2048
        v.cpus = 2
      end
    end
  end

end
