---

- hosts: all
  sudo: yes
  tasks:
  - name: Update apt-get
    apt: update_cache=yes

- hosts: zookeeper
  sudo: yes
  gather_facts: no
  roles:
    - zookeeper
  
- hosts: kafka
  sudo: yes
  gather_facts: no
  roles:
    - kafka

- hosts: ldap
  sudo: yes
  gather_facts: no
  roles:
    - ldap
