---
- name: Add Apt-Keys
  apt_key:
    id: "{{ docker_apt_key_sig }}"
    keyserver: "{{ docker_apt_key_url }}"
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    update_cache: yes
    state: present

- name: Install (or update) docker package
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if update_docker_package else 'present' }}"
    update_cache: yes
    cache_valid_time: 600
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - "{{ docker_pkg_name }}"

- name: Start Docker
  service: 
    name: "{{ docker_service_name }}" 
    state: restarted

- name: Install Docker-Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: "/usr/local/bin/docker-compose"
    force: "{{ 'yes' if update_docker_package else 'no' }}"

- name: Make Docker-Compose executable
  file:
    path: "/usr/local/bin/docker-compose"
    state: touch
    mode: "u+x,g+x,o+x"