---
- name: Update apt-get
  sudo: yes
  apt: update_cache=yes
- name: Install slapd
  sudo: yes
  apt: pkg=slapd state=present
- name: Install ldap-utils
  sudo: yes
  apt: pkg=ldap-utils state=present
  handlers:
    - name: config slapd
      sudo: yes
      command: dpkg-reconfigure slapd